### ISSUE TITLE
<link rel="stylesheet" [...] appearing before button

### ISSUE THREAD

**Issue by AmitLevinson** [fmmattioni/downloadthis#1]
Hey!
Love the package - such an easy implementation and aesthetic layout!
This was my first time trying the package in my blogdown hugo academic theme.

When serving the site localy and pushing online the button appears as follows:

![downloadthis](https://user-images.githubusercontent.com/55328033/79789524-048b8c80-8353-11ea-8b54-b5d564ae01a9.png)

Here's the code I used:
```r
library(downloadthis)

new_file <- elections %>% 
  select_if(~!is.list(.))

new_file %>% 
  download_this(
    output_name = "twitter election",
    output_extension = ".csv",
    button_label = "Download data as csv",
    button_type = "success",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
```

And here is my session info:
```
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] downloadthis_0.1.3

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4      bookdown_0.18   packrat_0.5.0   digest_0.6.25   later_1.0.0     mime_0.9        R6_2.4.1       
 [8] jsonlite_1.6.1  magrittr_1.5    evaluate_0.14   blogdown_0.18   stringi_1.4.6   rlang_0.4.5     rstudioapi_0.11
[15] promises_1.1.0  rmarkdown_2.1   tools_3.6.2     servr_0.16      stringr_1.4.0   httpuv_1.5.2    xfun_0.12      
[22] yaml_2.2.1      compiler_3.6.2  htmltools_0.4.0 knitr_1.28   
```

**Comment by fmmattioni** [comment]
Hi @AmitLevinson! Thank you very much for the kind feedback and for reporting this issue.

This may have been fixed here: b8b3840224da339ff73afca1473be5e781297be7. Could you give it a try and let me know if that works?

**Comment by AmitLevinson** [comment]
Hey!
Thanks for the quick reply.
I deleted and reinstalled the package but now it seems like similar issue (different link, same outcome):

![Untitled](https://user-images.githubusercontent.com/55328033/79849634-62f45180-83cb-11ea-92fc-38bfb90ea40b.png)

Maybe it's specific to my computer?

**Comment by fmmattioni** [comment]
Do you have this page online somewhere so I could take a look? It might be related to how hugo renders the page.. Unfortunately, I don't know much about Hugo, but I will see if I can find a solution for you.

**Comment by AmitLevinson** [comment]
Hey,
Yes, sorry, I didn't want to add it to the post live as it is kind of cumbersome.

For some reason now it also slows the loading of the page. See example here (scroll to the bottom):
https://amitlevinson.com/2020/04/20/israeli-elections-on-twitter/

I'll probably remove it later today or tomorrow if it doesn't work out.

Thank you very much for the help!

**Comment by fmmattioni** [comment]
Thank you! You can remove it now, I already extracted the information I need to see if I can fix it. I don't think this is an issue with {downloadthis}, but rather with the Hugo version. I did a quick test with my website here and I can't reproduce this error. I am using Hugo v0.48. I assume yours might a newer version? I will let you know as soon as I have some news. I have a couple of ideas, but I need to test them.

**Comment by AmitLevinson** [comment]
Yes, here's my version:

```
> blogdown::hugo_version()
[1] ‘0.69.0’
```
Thanks for the help and looking froward to be able and integrate it :)!

**Comment by fmmattioni** [comment]
Hi @AmitLevinson, I was just looking into this issue.. I have created a new website with the latest hugo version `0.69.2` and everything seems to be working:

https://condescending-perlman-012e96.netlify.app/post/2015-07-23-r-rmarkdown/#adding-download-button

Could you perhaps try updating your hugo version to see if that works?

**Comment by fmmattioni** [comment]
Plus, please also update `downloadthis` as it supports downloading `.rds` files now.

**Comment by AmitLevinson** [comment]
Hey,
Thanks for getting back to me.
it still doesn't work on my end - with the .csv it slows down my computer and the rendering is the same (adds the long link).
I tried with '.rds' file but it kept crashing, not sure why.

Thanks anyway, I'll give it another try next post!

**Comment by fmmattioni** [comment]
OK, thanks for trying it out! Do you mind if I fork your website repo to take a look?

**Comment by AmitLevinson** [comment]
Not at all!

Thanks :)

**Comment by fmmattioni** [comment]
It looks like this is related to this issue here: https://github.com/yihui/xfun/issues/23

I am going to add additional functions this week to handle this.

**Comment by fmmattioni** [comment]
For now, `download_link()` could be an alternative: 3a064c1273c0ace74a8d1ea0105535598b43d1b1

**Comment by AmitLevinson** [comment]
Thanks Felipe!
I think my cpu is cursed :( 
For now it doesn't crash but it generates a link and an unresponding button.
I'll give it a try in another post eventually.

Thanks for all your doing, I'd love to use it in the future.

![image](https://user-images.githubusercontent.com/55328033/81804618-114e6b00-9522-11ea-8c18-a096c601349f.png)

**Comment by fmmattioni** [comment]
Thanks for the update, @AmitLevinson! I still couldn't reproduce your issue here, but I will get back at it later this week. Please, let me know if you run into any more issues.
