### ISSUE TITLE
Plotly

### ISSUE THREAD

**Issue by Csmolarchuk** [fmmattioni/downloadthis#16]
Hi, 

I tried to use this package because it would be super useful. However, when I try to use it with plotly instead of ggplot2 it seems to shift all the text on the axes, so I haven't been able to use it. 

Thanks

**Comment by fmmattioni** [comment]
Hi @Csmolarchuk!

Thanks! Could you please provide a reproducible example?

**Comment by Csmolarchuk** [comment]
Sure! Below is some code that I ran in an rmd. When it gets knitted the y axis text gets shifted below the button. I had tried separating the graph and the button into separate chunks and that didn't seem to fix the issue either. 

---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, echo = FALSE, warning=FALSE, message=FALSE}
library(downloadthis)
library(plotly)
library(tidyverse)

data(mtcars)

plot_ly(mtcars %>% group_by(cyl, am) %>% tally(),
                          x= ~am, 
                          y= ~cyl,
                          type="bar") %>%
  layout( title ="mtcars", 
          xaxis=list(tickangle=90, title="AM"),
          yaxis=list (title="Here is some text for the axis"))


mtcars %>% 
  download_this(
    output_name = "mtcars dataset",
    output_extension = ".csv",
    button_label = "Download data as csv",
    button_type = "default",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
```

**Comment by fmmattioni** [comment]
Hi @Csmolarchuk,

I am sorry for the delay. I haven't been able to find a solution for this yet, so I am including in here the `help wanted` label. I will look at it further this week.

**Comment by alf-ken** [comment]
Hi, 

I've got the same problem. Interestingly, this happens, if you place the buttons under the plot. Placing it above the plot, the issue doesn't occur. 

Chris
