### ISSUE TITLE
[readr warning] The `path` argument of `write_xxx()` is deprecated as of readr 1.4.0.

### ISSUE THREAD

**Issue by sgaj** [fmmattioni/downloadthis#17]
Generating `.rds`/`.csv` download buttons triggers the following warning:

```
The `path` argument of `write_rds()` is deprecated as of readr 1.4.0
The `path` argument of `write_csv2()` is deprecated as of readr 1.4.0.
```

Should be an easy `path` > `file` replacement in https://github.com/fmmattioni/downloadthis/blob/master/R/download.R#L128-L132

If you want to be backwards compatible with older `readr` versions, you could implement the following solution:

```
if( packageVersion("readr") >= "1.4.0") {
  switch(output_extension,
    ".csv" = ifelse(csv2, readr::write_csv2(x = .data, file = tmp_file), readr::write_csv(x = .data, file = tmp_file)),
    ".xlsx" = writexl::write_xlsx(x = .data, path = tmp_file),
    ".rds" = readr::write_rds(x = .data, file = tmp_file)
  )
} else {
  switch(output_extension,
    ".csv" = ifelse(csv2, readr::write_csv2(x = .data, path = tmp_file), readr::write_csv(x = .data, path = tmp_file)),
    ".xlsx" = writexl::write_xlsx(x = .data, path = tmp_file),
    ".rds" = readr::write_rds(x = .data, path = tmp_file)
  )
}
```

### Summarized Session Info (packages)

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> package </th>
   <th style="text-align:left;"> loadedversion </th>
   <th style="text-align:left;"> source </th>
   <th style="text-align:left;"> date </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> downloadthis </td>
   <td style="text-align:left;"> 0.2.1 </td>
   <td style="text-align:left;"> Github (fmmattioni/downloadthis@05b61f7) </td>
   <td style="text-align:left;"> 2021-06-10 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> readr </td>
   <td style="text-align:left;"> 1.4.0 </td>
   <td style="text-align:left;"> CRAN (R 4.0.2) </td>
   <td style="text-align:left;"> 2020-10-05 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> writexl </td>
   <td style="text-align:left;"> 1.4.0 </td>
   <td style="text-align:left;"> CRAN (R 4.0.2) </td>
   <td style="text-align:left;"> 2021-04-20 </td>
  </tr>
</tbody>
</table>

**Comment by fmmattioni** [comment]
Hi, I am sorry for the delay.. this has now been fixed in #23
