### ISSUE TITLE
seems not working

### ISSUE THREAD

**Issue by marcofog** [fmmattioni/downloadthis#2]
The button is created but it seems non active...
I don't get any error...

b400_funnel_df %>%
  download_this(
    output_name = "funnel_dataset",
    output_extension = ".csv",
    button_label = "Download data as csv",
    button_type = "default",
    has_icon = TRUE,
    icon = "fa fa-save"
  )

> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.2                         
year           2019                        
month          12                          
day            12                          
svn rev        77560                       
language       R                           
version.string R version 3.6.2 (2019-12-12)
nickname       Dark and Stormy Night

**Comment by fmmattioni** [comment]
Hi @marcofog, thanks for filling the issue. Could you please provide a [reprex](https://www.tidyverse.org/help/) so I can reproduce your error?

**Comment by fmmattioni** [comment]
Also: which browser are you using?
