### ISSUE TITLE
Maybe have a parameter for the user to choose whether use write_csv2 or write_csv?

### ISSUE THREAD

**Issue by BILLBEATTHEPEAT** [fmmattioni/downloadthis#3]
Hey Felipe,

I am a user currently using this package in USA.  I have encountered a problem for the downloaded .csv file format. I have a .cvs file (comma delimited and using dot for decimal) set for download button, but after downloaded through `downloadthis::download_this` with `output_extension` set to be '.csv' it will be transferred into a .csv file with semicolon delimited and comma for decimal. 

I looked into your code and found that the writing function currently used is just write.csv2(), which is specifically used for semicolon delimited .csv file (code is here https://github.com/fmmattioni/downloadthis/blob/master/R/download.R#L108). But this format is not that usual in places outside Europe. So I am wondering whether it is possible to have a parameter for the users like me to choose the format we want to use for the output?

Thanks!

**Comment by fmmattioni** [comment]
Hi @BILLBEATTHEPEAT! Thanks for filling the issue. I am sorry for that, I have now added the argument `csv2` in `download_this()`.

You can achieve what you want setting this argument to `FALSE`:

```r
library(downloadthis)

mtcars %>% 
  download_this(
    output_name = "mtcars data set",
    output_extension = ".csv",
    button_label = "Download data",
    button_type = "warning",
    icon = "fa fa-save",
    csv2 = FALSE
  )
```

**Comment by BILLBEATTHEPEAT** [comment]
Thanks Felipe!
