### ISSUE TITLE
Window jumps to top of page when clicking download button 

### ISSUE THREAD

**Issue by daranzolin** [fmmattioni/downloadthis#30]
I have a long Quarto report with several `downloadthis` buttons. The buttons work great, but the window jumps to the top of the page after clicking, annoying some of my users. Is there someway to adjust the href argument here to prevent this behavior?

https://github.com/fmmattioni/downloadthis/blob/0718d0c0ae74868eb8ba42c72c18817d59cd1914/R/download.R#L268-L270

**Comment by fmmattioni** [comment]
Hi @daranzolin, could you provide me a quick reprex that I can reproduce this behavior?

**Comment by daranzolin** [comment]
Update: [this Stackoverflow solution works for single pages,](https://stackoverflow.com/a/75217579/5731890) but not when the output includes tabs.

**Comment by vincentmq** [comment]
+1 to this. Is there an update to this issue?
