### ISSUE TITLE
Add download pdf

### ISSUE THREAD

**Issue by Merguerrero** [fmmattioni/downloadthis#32]
Hi!
I found this project and R pakage very practical and I love it, thank you very much! I use it to make reports for my wet labs, and it would be great to be able to download plots as .pdf, as they are the best extension to later edit them with Illustrator, Inkscape, etc.

Thanks for your consideration

**Comment by scarioscia** [comment]
See [here](https://github.com/fmmattioni/downloadthis/blob/0718d0c0ae74868eb8ba42c72c18817d59cd1914/R/download.R#L180)

**Comment by fmmattioni** [comment]
thanks @scarioscia

**Comment by Merguerrero** [comment]
Sorry to bother again...

I'm reporting the results in quarto, and I'm generating plots in a for loop. Is there a way to have an independent button for each plot? My code is:

```{r}
for (gene in 1:length(ensebl_genes)){
      plot_gene<- ggplot(metadata, aes(x=Population, y=.data[[ensebl_genes[gene]]], 
fill = Population)) +  geom_boxplot() + theme(axis.text.x = element_text(angle=45,hjust=1)) +
 theme_minimal() +  scale_fill_viridis_d() + ylab("TPM") + ggtitle(genes[gene])
     print(plot_gene)
    
    download_this(plot_gene,output_name = "Plot",output_extension = ".pdf",
button_label = "Download this plot",button_type = "success")
}
```

And this is what I get in Quarto:

<img width="695" alt="Captura de pantalla 2024-12-13 a las 11 52 11" src="https://github.com/user-attachments/assets/55a980d0-e69e-42e8-88a6-137804b089f6" />

Any ideas? 

Thank you :D
