### ISSUE TITLE
Incompatible with Internet Explorer and Microsoft Edge

### ISSUE THREAD

**Issue by daranzolin** [fmmattioni/downloadthis#4]
Great package! However, I tried opening the rendered example inside IE and Edge, and it failed with both browsers.

Example used:
```
library(downloadthis)
mtcars %>% 
  download_this(
    output_name = "mtcars data set",
    output_extension = ".csv",
    button_label = "Download data",
    button_type = "warning",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
``` 

I realize support for IE may be impossible, but is Edge compatibility possible?

**Comment by fmmattioni** [comment]
Hi @daranzolin! Thanks for using `downloadthis`. You are correct, so far IE does not support embedded files. However, Edge should work depending on the version you are using. You can see more info here: https://caniuse.com/#feat=download.

Do you have the latest Edge version?

**Comment by daranzolin** [comment]
Ah, I did not have the latest version. Problem solved, thanks for letting me know!
