### ISSUE TITLE
Add Crosstalk compatibility

### ISSUE THREAD

**Issue by tvroylandt** [fmmattioni/downloadthis#5]
Thanks for this nice package. It helps a lot !

Would it be possible to add compatibility with `crosstalk` to download a custom selection ?

This question is linked to https://github.com/glin/reactable/issues/11

Thanks !

**Comment by fmmattioni** [comment]
Hi, @tvroylandt!

Thanks for your message. Yeah, I remember seeing this comment a few months ago but I forgot to check it. Thanks for filling the issue, this is going to remind me to give it a try. I will keep you posted!

**Comment by JohnCoene** [comment]
I don't think you can integrate {download_this} with crosstalk, it would not help addressing https://github.com/glin/reactable/issues/11 , this would take another form. Crosstalk is to highlight or filter points across htmlwidgets which {download_this} is not.

**Comment by landisrm** [comment]
I think you just need to extract the dataframe from the crosstalk object (or use the data.frame that was used to create the crosstalk object) and pass that to `download_this`.

**Comment by fmmattioni** [comment]
Thanks @landisrm, I am going to take a look at it later this week..
