### ISSUE TITLE
Download ggplot2

### ISSUE THREAD

**Issue by JohnCoene** [fmmattioni/downloadthis#7]
Hi Felipe,

Great work with the package!

Unless I am mistaken there is no function to download plots (namely ggplot2), I think it would be a great addition (probably more useful than downloading data) and looking at the source code it looks to me like you have everything in place to potentially support it.

Feel free to ask for a PR from me on that.

**Comment by fmmattioni** [comment]
Hi John!

That sounds like a great idea! Would you mind making a PR? I would love to see what you have in mind :-)
