### ISSUE TITLE
Idea: simplify arguments

### ISSUE THREAD

**Issue by JohnCoene** [fmmattioni/downloadthis#8]
Just a thought to simplify the arguments.

```r
foo <- function(output){
  ext <- tools::file_ext(output)
}
```

This would allow 1) removing `output_extension` file and 2) perhaps would make the `output` argument somewhat clearer than `output_name` in which some, I assume, might erroneously specify the extension, e.g.: `download_this(cars, "cars.csv")`

**Comment by fmmattioni** [comment]
Hi John!

I believe this is a good idea. What do you think is the best way of doing it? Can we deprecate an argument? Perhaps throwing a warning?

**Comment by JohnCoene** [comment]
Hi Felipe,

I'm no longer sure this is a good idea 😃 

The new method with methods and automatic name generation makes it such that the `output_name` and `output_extension` do not have to be specified explicitly. 

Currently one can do.

```r
# downloads cars.csv
download_this(mtcars)
```

What I suggested in this issue would break that as one would have to specify an `output_name`.

```r
download_this(mtcars, output_name = 'cars.csv')
```

This could perhaps be implemented if the name of output is not generated by the function automatically and defaults to a string 

```r
download_this <- function(mtcars, output_name = "data.csv", ...){...}
```

Moreover this would make listing the possible output formats more difficult. The way you had it initially is probably better.

Sorry it seemed like a good idea at the time. Do you see a better way of doing it?

**Comment by fmmattioni** [comment]
Hi John!

That is true.. by the way, I really liked the way the function call was simplified. I will close this for now, but we can revisit it in the future if needed.

Thank you!

**Comment by JohnCoene** [comment]
No no, thanks to you for the great package :)
